### ISSUE TITLE
Key value support?

### ISSUE THREAD

**Issue by DanielLarsenNZ** [fermyon/spin-dotnet-sdk#63]
Does / can .NET SDK support the Spin Key Value Store component? For example:

```toml
# in spin.toml
[[component]]
key_value_stores = ["default"]

# in rt-config.toml
[key_value_store.default]
type = "azure_cosmos"
key = "UmVhbGx..."
account = "cosmos-spin-1233"
database = "cosmos-sql-spin"
container = "kv"
```

As per https://www.thorsten-hans.com/azure-cosmos-db-as-key-value-store-for-fermyon-spin/
